drop schema if exists perf_schemaX;
create schema perf_schemaX;
use perf_schemaX;

-- files_by_io
-- files_by_io

CREATE  VIEW `files_by_io` AS select `performance_schema`.`file_summary_by_instance`.`FILE_NAME` AS `file_name`,`performance_schema`.`file_summary_by_instance`.`COUNT_READ` AS `count_read`,format(`performance_schema`.`file_summary_by_instance`.`SUM_NUMBER_OF_BYTES_READ`,0) AS `total_read`,ifnull(`performance_schema`.`file_summary_by_instance`.`SUM_NUMBER_OF_BYTES_READ` / `performance_schema`.`file_summary_by_instance`.`COUNT_READ`,0.00) AS `avg_read`,`performance_schema`.`file_summary_by_instance`.`COUNT_WRITE` AS `count_write`,format(`performance_schema`.`file_summary_by_instance`.`SUM_NUMBER_OF_BYTES_WRITE`,0) AS `total_write`,ifnull(`performance_schema`.`file_summary_by_instance`.`SUM_NUMBER_OF_BYTES_WRITE` / `performance_schema`.`file_summary_by_instance`.`COUNT_WRITE`,0.00) AS `avg_write`,format(`performance_schema`.`file_summary_by_instance`.`SUM_NUMBER_OF_BYTES_READ` + `performance_schema`.`file_summary_by_instance`.`SUM_NUMBER_OF_BYTES_WRITE`,0) AS `total`,ifnull(round(100 - `performance_schema`.`file_summary_by_instance`.`SUM_NUMBER_OF_BYTES_READ` / (`performance_schema`.`file_summary_by_instance`.`SUM_NUMBER_OF_BYTES_READ` + `performance_schema`.`file_summary_by_instance`.`SUM_NUMBER_OF_BYTES_WRITE`) * 100,2),0.00) AS `write_pct` from `performance_schema`.`file_summary_by_instance`;
-- statements_history
-- statements_history

CREATE  VIEW `statements_history` AS select `B`.`PROCESSLIST_USER` AS `user`,`B`.`PROCESSLIST_HOST` AS `host`,`B`.`CONNECTION_TYPE` AS `connection_type`,regexp_substr(`A`.`EVENT_NAME`,'([^/]*)$') AS `event_type`,`A`.`TIMER_WAIT` / 1000000000000 AS `waiting_locks`,`A`.`SQL_TEXT` AS `sql_text`,`A`.`CURRENT_SCHEMA` AS `current_schema`,`A`.`MYSQL_ERRNO` AS `mysql_errno`,`A`.`MESSAGE_TEXT` AS `message_text`,`A`.`ERRORS` AS `errors`,`A`.`WARNINGS` AS `warnings`,`A`.`ROWS_AFFECTED` AS `rows_affected`,`A`.`ROWS_SENT` AS `rows_sent`,`A`.`ROWS_EXAMINED` AS `rows_examined`,`A`.`CREATED_TMP_DISK_TABLES` AS `created_tmp_disk_tables`,`A`.`CREATED_TMP_TABLES` AS `created_tmp_tables`,`A`.`SELECT_FULL_JOIN` AS `select_full_join`,`A`.`SELECT_FULL_RANGE_JOIN` AS `select_full_range_join`,`A`.`SELECT_RANGE` AS `select_range`,`A`.`SELECT_RANGE_CHECK` AS `select_range_check`,`A`.`SELECT_SCAN` AS `select_scan`,`A`.`SORT_MERGE_PASSES` AS `sort_merge_passes`,`A`.`SORT_RANGE` AS `sort_range`,`A`.`SORT_ROWS` AS `sort_rows`,`A`.`SORT_SCAN` AS `sort_scan`,`A`.`NO_INDEX_USED` AS `no_index_used`,`A`.`NO_GOOD_INDEX_USED` AS `no_good_index_used` from (`performance_schema`.`events_statements_history` `A` left join `performance_schema`.`threads` `B` on(`A`.`THREAD_ID` = `B`.`THREAD_ID`)) where regexp_substr(`A`.`EVENT_NAME`,'([^/]*)$') <> 'Ping';
-- statements_history_long
-- statements_history_long

CREATE  VIEW `statements_history_long` AS select `B`.`PROCESSLIST_USER` AS `user`,`B`.`PROCESSLIST_HOST` AS `host`,`B`.`CONNECTION_TYPE` AS `connection_type`,regexp_substr(`A`.`EVENT_NAME`,'([^/]*)$') AS `event_type`,`A`.`TIMER_WAIT` / 1000000000000 AS `waiting_locks`,`A`.`SQL_TEXT` AS `sql_text`,`A`.`CURRENT_SCHEMA` AS `current_schema`,`A`.`MYSQL_ERRNO` AS `mysql_errno`,`A`.`MESSAGE_TEXT` AS `message_text`,`A`.`ERRORS` AS `errors`,`A`.`WARNINGS` AS `warnings`,`A`.`ROWS_AFFECTED` AS `rows_affected`,`A`.`ROWS_SENT` AS `rows_sent`,`A`.`ROWS_EXAMINED` AS `rows_examined`,`A`.`CREATED_TMP_DISK_TABLES` AS `created_tmp_disk_tables`,`A`.`CREATED_TMP_TABLES` AS `created_tmp_tables`,`A`.`SELECT_FULL_JOIN` AS `select_full_join`,`A`.`SELECT_FULL_RANGE_JOIN` AS `select_full_range_join`,`A`.`SELECT_RANGE` AS `select_range`,`A`.`SELECT_RANGE_CHECK` AS `select_range_check`,`A`.`SELECT_SCAN` AS `select_scan`,`A`.`SORT_MERGE_PASSES` AS `sort_merge_passes`,`A`.`SORT_RANGE` AS `sort_range`,`A`.`SORT_ROWS` AS `sort_rows`,`A`.`SORT_SCAN` AS `sort_scan`,`A`.`NO_INDEX_USED` AS `no_index_used`,`A`.`NO_GOOD_INDEX_USED` AS `no_good_index_used` from (`performance_schema`.`events_statements_history_long` `A` left join `performance_schema`.`threads` `B` on(`A`.`THREAD_ID` = `B`.`THREAD_ID`)) where regexp_substr(`A`.`EVENT_NAME`,'([^/]*)$') <> 'Ping';
-- tables_by_statement_type
-- tables_by_statement_type

CREATE  VIEW `tables_by_statement_type` AS select `performance_schema`.`table_io_waits_summary_by_table`.`OBJECT_SCHEMA` AS `tbl_schema`,`performance_schema`.`table_io_waits_summary_by_table`.`OBJECT_NAME` AS `tbl`,`performance_schema`.`table_io_waits_summary_by_table`.`COUNT_FETCH` AS `rows_fetched`,`performance_schema`.`table_io_waits_summary_by_table`.`COUNT_INSERT` AS `rows_inserted`,`performance_schema`.`table_io_waits_summary_by_table`.`COUNT_UPDATE` AS `rows_updated`,`performance_schema`.`table_io_waits_summary_by_table`.`COUNT_DELETE` AS `rows_deleted`,format(`performance_schema`.`table_io_waits_summary_by_table`.`AVG_TIMER_WAIT` / 1000000000000,8) AS `avg_latency_scnds` from `performance_schema`.`table_io_waits_summary_by_table` where `performance_schema`.`table_io_waits_summary_by_table`.`COUNT_FETCH` + `performance_schema`.`table_io_waits_summary_by_table`.`COUNT_INSERT` + `performance_schema`.`table_io_waits_summary_by_table`.`COUNT_UPDATE` + `performance_schema`.`table_io_waits_summary_by_table`.`COUNT_DELETE` <> 0;
-- tables_with_full_table_scans
-- tables_with_full_table_scans

CREATE  VIEW `tables_with_full_table_scans` AS select `performance_schema`.`table_io_waits_summary_by_index_usage`.`OBJECT_SCHEMA` AS `object_schema`,`performance_schema`.`table_io_waits_summary_by_index_usage`.`OBJECT_NAME` AS `object_name`,format(`performance_schema`.`table_io_waits_summary_by_index_usage`.`COUNT_READ`,0) AS `rows_full_scanned` from `performance_schema`.`table_io_waits_summary_by_index_usage` where `performance_schema`.`table_io_waits_summary_by_index_usage`.`INDEX_NAME` is null and `performance_schema`.`table_io_waits_summary_by_index_usage`.`COUNT_READ` > 0;
-- tables_with_unused_indexes
-- tables_with_unused_indexes

CREATE  VIEW `tables_with_unused_indexes` AS select `performance_schema`.`table_io_waits_summary_by_index_usage`.`OBJECT_SCHEMA` AS `table_schema`,`performance_schema`.`table_io_waits_summary_by_index_usage`.`OBJECT_NAME` AS `table_name`,`performance_schema`.`table_io_waits_summary_by_index_usage`.`INDEX_NAME` AS `index_name` from `performance_schema`.`table_io_waits_summary_by_index_usage` where `performance_schema`.`table_io_waits_summary_by_index_usage`.`INDEX_NAME` is not null and `performance_schema`.`table_io_waits_summary_by_index_usage`.`COUNT_STAR` = 0;
-- users_by_connection
-- users_by_connection

CREATE  VIEW `users_by_connection` AS select `performance_schema`.`accounts`.`USER` AS `user`,`performance_schema`.`accounts`.`HOST` AS `host`,`performance_schema`.`accounts`.`CURRENT_CONNECTIONS` AS `current_connections`,`performance_schema`.`accounts`.`TOTAL_CONNECTIONS` AS `total_connections` from `performance_schema`.`accounts` where `performance_schema`.`accounts`.`USER` is not null;
-- users_by_io_latency
-- users_by_io_latency

CREATE  VIEW `users_by_io_latency` AS select `performance_schema`.`events_waits_summary_by_user_by_event_name`.`USER` AS `user`,sum(`performance_schema`.`events_waits_summary_by_user_by_event_name`.`COUNT_STAR`) AS `events_count`,format(sum(`performance_schema`.`events_waits_summary_by_user_by_event_name`.`SUM_TIMER_WAIT`) / 1000000000000,8) AS `total_latency_scnds`,format(sum(`performance_schema`.`events_waits_summary_by_user_by_event_name`.`SUM_TIMER_WAIT`) / sum(`performance_schema`.`events_waits_summary_by_user_by_event_name`.`COUNT_STAR`) / 1000000000000,8) AS `average_latency_per_io_event_scnds` from `performance_schema`.`events_waits_summary_by_user_by_event_name` where `performance_schema`.`events_waits_summary_by_user_by_event_name`.`EVENT_NAME` like 'wait/io/file/%' and `performance_schema`.`events_waits_summary_by_user_by_event_name`.`USER` is not null and `performance_schema`.`events_waits_summary_by_user_by_event_name`.`COUNT_STAR` <> 0 group by `performance_schema`.`events_waits_summary_by_user_by_event_name`.`USER`;
-- users_by_select_statement_latency
-- users_by_select_statement_latency

CREATE  VIEW `users_by_select_statement_latency` AS select `performance_schema`.`events_statements_summary_by_user_by_event_name`.`USER` AS `user`,`performance_schema`.`events_statements_summary_by_user_by_event_name`.`COUNT_STAR` AS `select_count`,format(`performance_schema`.`events_statements_summary_by_user_by_event_name`.`SUM_TIMER_WAIT` / 1000000000000,8) AS `total_latency_scnds`,format(`performance_schema`.`events_statements_summary_by_user_by_event_name`.`AVG_TIMER_WAIT` / 1000000000000,8) AS `average_latency_per_select_scnds` from `performance_schema`.`events_statements_summary_by_user_by_event_name` where `performance_schema`.`events_statements_summary_by_user_by_event_name`.`EVENT_NAME` = 'statement/sql/select' and `performance_schema`.`events_statements_summary_by_user_by_event_name`.`USER` is not null and `performance_schema`.`events_statements_summary_by_user_by_event_name`.`COUNT_STAR` <> 0;
